# KNN Algorithm

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import neighbors
from sklearn.metrics import accuracy_score, confusion_matrix

In [4]:
knn_data = pd.read_csv("train.csv")

In [5]:
knn_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
knn_data = knn_data.drop(["Cabin"], axis=1)

In [7]:
knn_data["Fare"] = np.round_(knn_data["Fare"])

In [10]:
knn_data = knn_data.drop(["Name","Ticket","PassengerId"], axis=1)

In [11]:
le = LabelEncoder()

In [12]:
knn_data["Sex"] = le.fit_transform(knn_data["Sex"])
knn_data["Embarked"] = le.fit_transform(knn_data["Embarked"])
knn_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
0         0       3    1  22.0      1      0   7.0         2
1         1       1    0  38.0      1      0  71.0         0
2         1       3    0  26.0      0      0   8.0         2
3         1       1    0  35.0      1      0  53.0         2
4         0       3    1  35.0      0      0   8.0         2

In [18]:
y = knn_data["Pclass"]
x = knn_data.drop(["Pclass"], axis=1)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [22]:
acc_scores = dict()
def KNN(k):
    knn = neighbors.KNeighborsClassifier(n_neighbors = k)
    print(f"Accuracy score based on k = {k} \n{round(knn.fit(X_train,y_train).score(X_test,y_test)*100,4)}\n")

    pred1 = knn.predict(X_test)
    conf = confusion_matrix(y_test, pred1)
    print(f"Confusion Matrix: \n{conf}")

    
    print("*************************************************************************************")

In [23]:
for x in range (1,623):
    KNN(x)

Accuracy score based on k = 1 
87.6404

Confusion Matrix: 
[[ 61   7   2]
 [  3  35  11]
 [  1   9 138]]
*************************************************************************************
Accuracy score based on k = 2 
86.1423

Confusion Matrix: 
[[ 67   2   1]
 [  7  37   5]
 [  4  18 126]]
*************************************************************************************
Accuracy score based on k = 3 
84.6442

Confusion Matrix: 
[[ 60   7   3]
 [  7  26  16]
 [  3   5 140]]
*************************************************************************************
Accuracy score based on k = 4 
82.0225

Confusion Matrix: 
[[ 61   6   3]
 [  8  28  13]
 [  3  15 130]]
*************************************************************************************
Accuracy score based on k = 5 
84.2697

Confusion Matrix: 
[[ 59   9   2]
 [  7  27  15]
 [  3   6 139]]
*************************************************************************************
Accuracy score based on k = 6 
84.6442

Confu

Accuracy score based on k = 44 
77.9026

Confusion Matrix: 
[[ 61   7   2]
 [  7  18  24]
 [  7  12 129]]
*************************************************************************************
Accuracy score based on k = 45 
77.9026

Confusion Matrix: 
[[ 61   7   2]
 [  7  18  24]
 [  7  12 129]]
*************************************************************************************
Accuracy score based on k = 46 
78.2772

Confusion Matrix: 
[[ 61   7   2]
 [  7  17  25]
 [  5  12 131]]
*************************************************************************************
Accuracy score based on k = 47 
77.5281

Confusion Matrix: 
[[ 61   7   2]
 [  7  15  27]
 [  5  12 131]]
*************************************************************************************
Accuracy score based on k = 48 
77.5281

Confusion Matrix: 
[[ 61   7   2]
 [  7  15  27]
 [  5  12 131]]
*************************************************************************************
Accuracy score based on k = 49 
78.2772


Accuracy score based on k = 88 
75.2809

Confusion Matrix: 
[[ 54   5  11]
 [  5  10  34]
 [  5   6 137]]
*************************************************************************************
Accuracy score based on k = 89 
75.6554

Confusion Matrix: 
[[ 54   6  10]
 [  5  10  34]
 [  5   5 138]]
*************************************************************************************
Accuracy score based on k = 90 
75.6554

Confusion Matrix: 
[[ 54   5  11]
 [  5  10  34]
 [  5   5 138]]
*************************************************************************************
Accuracy score based on k = 91 
75.6554

Confusion Matrix: 
[[ 54   6  10]
 [  5  10  34]
 [  5   5 138]]
*************************************************************************************
Accuracy score based on k = 92 
75.6554

Confusion Matrix: 
[[ 54   6  10]
 [  5  10  34]
 [  5   5 138]]
*************************************************************************************
Accuracy score based on k = 93 
75.6554


Accuracy score based on k = 133 
76.03

Confusion Matrix: 
[[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
*************************************************************************************
Accuracy score based on k = 134 
76.03

Confusion Matrix: 
[[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
*************************************************************************************
Accuracy score based on k = 135 
76.03

Confusion Matrix: 
[[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
*************************************************************************************
Accuracy score based on k = 136 
76.03

Confusion Matrix: 
[[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
*************************************************************************************
Accuracy score based on k = 137 
76.03

Confusion Matrix: 
[[ 52  13   5]
 [  5  11  33]
 [  5   3 140]]
*************************************************************************************
Accuracy score based on k = 138 
75.6554

Con

Accuracy score based on k = 177 
75.6554

Confusion Matrix: 
[[ 52   6  12]
 [  5   7  37]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 178 
75.2809

Confusion Matrix: 
[[ 52   5  13]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 179 
75.2809

Confusion Matrix: 
[[ 52   5  13]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 180 
75.2809

Confusion Matrix: 
[[ 52   5  13]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 181 
75.2809

Confusion Matrix: 
[[ 52   5  13]
 [  5   6  38]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 182 
75

 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 220 
72.2846

Confusion Matrix: 
[[ 48   4  18]
 [  4   2  43]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 221 
72.2846

Confusion Matrix: 
[[ 48   4  18]
 [  4   2  43]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 222 
72.2846

Confusion Matrix: 
[[ 48   4  18]
 [  4   2  43]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 223 
72.2846

Confusion Matrix: 
[[ 48   1  21]
 [  4   2  43]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 224 
72.2846

Confusion Matrix: 
[[ 48   1  21]
 [  4   2  43]
 [  5   0 143]]
*******************

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 264 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 265 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 266 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 267 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 [  4   1  44]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 268 
71.9101

Confusion Matrix: 
[[ 48   0  22]
 

Confusion Matrix: 
[[ 45   0  25]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 307 
70.0375

Confusion Matrix: 
[[ 44   0  26]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 308 
70.0375

Confusion Matrix: 
[[ 44   0  26]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 309 
70.412

Confusion Matrix: 
[[ 45   0  25]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 310 
69.6629

Confusion Matrix: 
[[ 43   0  27]
 [  4   0  45]
 [  5   0 143]]
*************************************************************************************
Accuracy score based on k = 311 
69.6629

Confusion Matrix: 
[[ 43   1  26]
 [

Confusion Matrix: 
[[ 28   1  41]
 [  1   0  48]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 351 
65.9176

Confusion Matrix: 
[[ 28   1  41]
 [  1   0  48]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 352 
65.9176

Confusion Matrix: 
[[ 28   0  42]
 [  1   0  48]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 353 
65.9176

Confusion Matrix: 
[[ 28   0  42]
 [  1   0  48]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 354 
65.9176

Confusion Matrix: 
[[ 28   0  42]
 [  1   0  48]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 355 
65.9176

Confusion Matrix: 
[[ 28   1  41]
 

Accuracy score based on k = 393 
59.5506

Confusion Matrix: 
[[ 11   0  59]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 394 
59.5506

Confusion Matrix: 
[[ 11   0  59]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 395 
58.8015

Confusion Matrix: 
[[  9   0  61]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 396 
58.8015

Confusion Matrix: 
[[  9   0  61]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 397 
58.8015

Confusion Matrix: 
[[  9   0  61]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 398 
58

Accuracy score based on k = 436 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 437 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 438 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 439 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 440 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 441 
55

 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 480 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 481 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 482 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 483 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 484 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*******************

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 523 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 524 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 525 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 526 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 527 
55.4307

Confusion Matrix: 
[[  0   0  70]
 

Accuracy score based on k = 566 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 567 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 568 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 569 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 570 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 571 
55

 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 609 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 610 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 611 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 612 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*************************************************************************************
Accuracy score based on k = 613 
55.4307

Confusion Matrix: 
[[  0   0  70]
 [  0   0  49]
 [  0   0 148]]
*******************

# SVM

In [24]:
from sklearn import svm

In [27]:
svm_data = pd.read_csv("train.csv")

In [28]:
svm_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [30]:
svm_data = svm_data.drop(["Name","Ticket","PassengerId","Cabin"], axis=1)

In [32]:
svm_data["Fare"] = np.round_(svm_data["Fare"])

In [33]:
svm_data["Sex"] = le.fit_transform(svm_data["Sex"])
svm_data["Embarked"] = le.fit_transform(svm_data["Embarked"])
svm_data.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
0         0       3    1  22.0      1      0   7.0         2
1         1       1    0  38.0      1      0  71.0         0
2         1       3    0  26.0      0      0   8.0         2
3         1       1    0  35.0      1      0  53.0         2
4         0       3    1  35.0      0      0   8.0         2

In [34]:
y = svm_data["Pclass"]
x = svm_data.drop(["Pclass"], axis=1)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [36]:
clf = svm.SVC(gamma = 0.01, C = 100)

def SVM(x, y):
    X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.3, random_state = 0)
    y_pred = clf.fit(X_train, y_train).predict(X_test)
    acc = round(accuracy_score(y_test, y_pred, normalize = True) * 100, 2)
    confm = confusion_matrix(y_test, y_pred)
    return [acc, confm]

In [39]:
models = []
for enum, i in enumerate(svm_data.columns):
    if i == 'Age' or i == 'Fare':
        continue
    y = svm_data.iloc[:, enum:enum+1]
    x = svm_data.drop(columns = y.columns)
    models.append([SVM(x, y), y.columns[0]])

C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

In [42]:
for _ in models:
    print(f'{_[1]} vs {str(svm_data.drop([_[1]], axis=1).columns.to_list()).strip("[]")}\n')
    print(f'Accuracy: {_[0][0]}')
    print(f'Confusion Matrix: \n {_[0][1]}\n')
    print(f"Out of total 267 records only {np.trace(_[0][1])} are successfully classified, giving a model accuracy of\
          {_[0][0]}%.")
    print('\n-----------------------\n')

Survived vs 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'

Accuracy: 73.03
Confusion Matrix: 
 [[123  34]
 [ 38  72]]

Out of total 267 records only 195 are successfully classified, giving a model accuracy of          73.03%.

-----------------------

Pclass vs 'Survived', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'

Accuracy: 88.76
Confusion Matrix: 
 [[ 64   4   2]
 [  4  34  11]
 [  1   8 139]]

Out of total 267 records only 237 are successfully classified, giving a model accuracy of          88.76%.

-----------------------

Sex vs 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'

Accuracy: 73.03
Confusion Matrix: 
 [[ 66  32]
 [ 40 129]]

Out of total 267 records only 195 are successfully classified, giving a model accuracy of          73.03%.

-----------------------

SibSp vs 'Survived', 'Pclass', 'Sex', 'Age', 'Parch', 'Fare', 'Embarked'

Accuracy: 76.03
Confusion Matrix: 
 [[153  23   5   0   1   0   0]
 [ 21  39   4   1   0   0   0]
 [  