# Titanic Dataset

In [12]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv("train.csv")

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    object 
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Fare      889 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.7+ KB


In [5]:
data = data.drop(["PassengerId","Name","Ticket","Cabin"],axis=1)

In [9]:
data["Fare"] = np.round_(data["Fare"])

In [10]:
data.head()

Survived  Pclass     Sex   Age  SibSp  Parch  Fare Embarked
0         0       3    male  22.0      1      0   7.0        S
1         1       1  female  38.0      1      0  71.0        C
2         1       3  female  26.0      0      0   8.0        S
3         1       1  female  35.0      1      0  53.0        S
4         0       3    male  35.0      0      0   8.0        S

In [14]:
le = LabelEncoder()

In [15]:
data["Sex"] = le.fit_transform(data["Sex"])

In [16]:
data["Embarked"] = le.fit_transform(data["Embarked"])

In [17]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Fare  Embarked
0         0       3    1  22.0      1      0   7.0         2
1         1       1    0  38.0      1      0  71.0         0
2         1       3    0  26.0      0      0   8.0         2
3         1       1    0  35.0      1      0  53.0         2
4         0       3    1  35.0      0      0   8.0         2

In [18]:
clf = BernoulliNB()

In [46]:
def naivebayes (x,y,rstate):
    X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    acc = accuracy_score(y_test,y_pred)
    conf = confusion_matrix(y_test,y_pred)
    return (acc,conf)

In [25]:
data.columns 

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='object')

In [51]:
rstate=-1
models = []

for enum, i in enumerate(data.columns[1:]):
    if i == 'Age' or i == 'Fare':
        continue
    y = data.iloc[:, enum+1:enum+2]
    x = data.drop(columns = y.columns)
    rstate += 1
    models.append([naivebayes(x, y, rstate), y.columns[0]])

C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ravi kiran\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of 

In [60]:
for j in models:
    print(f'{j[1]} vs All\n')
    print(f'Accuracy: {j[0][0]}')
    print(f'Confusion Matrix: \n {j[0][1]}\n')
    print(f"Out of total 267 records only {np.trace(j[0][1])} are successfully classified, giving a model accuracy of \
    {int(j[0][0]*100)}%.")
    print('\n-----------------------\n')

Pclass vs All

Accuracy: 0.5917602996254682
Confusion Matrix: 
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]

Out of total 267 records only 158 are successfully classified, giving a model accuracy of     59%.

-----------------------

Sex vs All

Accuracy: 0.7453183520599251
Confusion Matrix: 
 [[ 49  49]
 [ 19 150]]

Out of total 267 records only 199 are successfully classified, giving a model accuracy of     74%.

-----------------------

SibSp vs All

Accuracy: 0.6891385767790262
Confusion Matrix: 
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]

Out of total 267 records only 184 are successfully classified, giving a model accuracy of     68%.

-----------------------

Parch vs All

Accuracy: 0.7153558052434457
Confusion Matrix: 
 [[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0  