# 1. Create a 3x3x3 array with random values 

In [3]:
import numpy as np

In [4]:
a = np.random.random((3,3,3))
print(a)

[[[0.50835007 0.21083055 0.51432404]
  [0.38538389 0.72530701 0.15014652]
  [0.8058684  0.91130416 0.19398678]]

 [[0.09544221 0.09295197 0.4192701 ]
  [0.3285947  0.0901008  0.63728125]
  [0.22278064 0.43822479 0.02218906]]

 [[0.06966859 0.30018547 0.63795689]
  [0.86688945 0.29752994 0.99895165]
  [0.29670466 0.56125508 0.88784276]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
z = np.diag(1+np.arange(4), k = -1)
print (z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
x = np.zeros((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [11]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.94752686 0.88749794 0.76481269 0.13421352 0.11409493]
 [0.02477857 0.8776832  0.44192908 0.00920053 0.        ]
 [0.5471755  0.81082793 0.33505117 0.94212945 0.57017717]
 [0.00929668 0.36933316 0.06908842 0.47741773 1.        ]
 [0.4476358  0.11128319 0.40384539 0.08327034 0.39582968]]


# 5.  How to find common values between two arrays?

In [20]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [21]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [32]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
equal = np.allclose(a,b)
print(equal)

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [35]:
y = np.random.random(10)
y[y.argmax()] = 0
print(y)

[0.783522   0.64113639 0.65114931 0.         0.34927201 0.41204973
 0.4517748  0.27411557 0.20515218 0.39183239]


# 9. How to print all the values of an array?

In [22]:
np.set_printoptions(threshold=np.nan)
v = np.zeros((25,25))
print(v)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

# 10.Subtract the mean of each row of a matrix

In [37]:
x = np.random.rand(5, 10)

# Recent versions of numpy
y = x - x.mean(axis=1, keepdims=True)
y

array([[-0.01569619,  0.37153712, -0.06224778, -0.17760032,  0.27762162,
        -0.15839216,  0.17970948, -0.26484796, -0.2716671 ,  0.1215833 ],
       [ 0.03685114, -0.2946006 ,  0.11222855,  0.50912735,  0.27006659,
        -0.22435889, -0.31625645, -0.23946969, -0.34570811,  0.4921201 ],
       [-0.16871853,  0.36448905,  0.05284176,  0.17472493,  0.4224617 ,
        -0.27129327, -0.3629741 ,  0.05680013, -0.51791787,  0.2495862 ],
       [-0.07835534, -0.36698526, -0.37453336, -0.01693919, -0.37300865,
         0.31219151,  0.37707674, -0.07102292,  0.11063403,  0.48094244],
       [-0.1802649 ,  0.02820239,  0.43429397, -0.07369548, -0.27590826,
         0.02504894,  0.00548555,  0.11642504, -0.02848435, -0.05110288]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [38]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 1. 3. 5. 1. 6. 3. 1. 4.]


# 12.How to get the diagonal of a dot product?

In [41]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

np.diag(np.dot(A, B))

array([120,  36,  25])

# 13.How to find the most frequent value in an array?

In [39]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[0 7 3 8 2 8 3 6 2 7 9 3 6 3 4 5 8 8 1 0 3 9 3 0 4 3 2 2 1 3 0 4 8 8 2 9 9
 7 1 5 3 5 2 5 7 2 4 7 8 3]
rank: 3


# 14.How to get the n largest values of an array

In [40]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9995 9996 9998 9997]


# 15.How to create a record array from a regular array?

In [43]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
R

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])